### ISSUE TITLE
Improve ``rm`` command

### ISSUE THREAD

**Issue by ChacaS0** [ChacaS0/tempest#21]
## In short
The ``tempest rm`` is a nice command but not so convenient to use. It just needs some enhancement.

## Examples
We should be able to remove targets from the **TEMPest** list with a command like ``tempest rm -i 0-2`` or ``tempest rm -i 0 3`` or ``tempest -p /path1 /path2``

## In depth
So the ``0-2`` would remove all targets from 0 to 2 from **TEMPest** list.
``0 3`` would remove targets with index ``0`` and ``3``.
Should be able to do the same with the full path name.

## In addition
Update and/or create documentation about that
:heavy_plus_sign: Use this opportunity to finish the ``--origin`` flag :stuck_out_tongue_winking_eye: 

## TODOs
 

- [x] add the thing
- [x]  write the code ofc
- [x]  write doc
- [x]  udpate tests
- [x] update ``rm`` tutorial (``gh-pages``)
- [x] same for ``--origin``

**Comment by ChacaS0** [comment]
:bug::exclamation: After 856d8d8, using ``rm`` on multiple values doesn't and duplicates some targets

**Comment by ChacaS0** [comment]
TODO: doc stuff
