### ISSUE TITLE
Auto add temp.est directories

### ISSUE THREAD

**Issue by MuchChaca** [ChacaS0/tempest#31]
## Globally
Look for all ``temp.est`` directories of the system and add them to the ``targets list`` of **TEMPest** if they are not already there.

## Usage
Should be something like:
```bash
> tempest add --auto
```
Then maybe display a little warning message about the time it would take and to confirm ?
At the end, shows what targets were added.

## TODOs
- [x] Actual code that would search those directories.
- [x] Tests for the research.
- [x] Code to add the matching directories
- [x] Tests for the add.

**Comment by ChacaS0** [comment]
First: #32
