### ISSUE TITLE
Generate a new target

### ISSUE THREAD

**Issue by MuchChaca** [ChacaS0/tempest#32]
## Gloablly
The ability to generate a new target in the current directory or in a specified one. This "new target" would be added automatically in the targets list of **TEMPest** and would already have the typed name referred in #31 like ``temp.est`` or whatever will be used there. 

## Usage 
* A new target in the current directory:
```bash
> tempest new
```
* A new target in the ``/temp`` directory:
```bash
> tempest new /temp
```

## TODOs
- [x] Actual code for the current directory
- [x] Tests for the current directory functionnality
- [x] Code for the named directory
- [x] Tests for the named directory functionnality
